#!/usr/bin/env bash
export PATH
source /etc/os-release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
cat << EOF | sudo debconf-set-selections
# Abort kernel # Abort kernel removal??
linux-base	linux-base/removing-running-kernel	boolean	false
EOF

optimizing_system() {
	#wget -O /etc/sysctl.conf "https://github.com/FighterTunnel/tunnel/raw/main/fodder/FighterTunnel-examples/Documentation/sysctl.conf" >/dev/null 2>&1
	sysctl -p
	echo "*               soft    nofile           1000000
*               hard    nofile          1000000" >/etc/security/limits.conf
	echo "ulimit -SHn 1000000" >>/etc/profile
}
startbbr() {
	#remove_all
	if [[ $(echo ${kernel_version} | awk -F'.' '{print $1}') -ge "5" ]]; then
		echo "net.core.default_qdisc=cake" >>/etc/sysctl.conf
		echo "net.ipv4.tcp_congestion_control=bbr" >>/etc/sysctl.conf
	else
		echo "net.core.default_qdisc=fq" >>/etc/sysctl.conf
		echo "net.ipv4.tcp_congestion_control=bbr" >>/etc/sysctl.conf
	fi
	sysctl -p
}
startbbr
#apt-get --fix-broken install -y && apt-get autoremove -y
#optimizing_system
