#!/bin/bash
ETH=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1)
cat >/usr/bin/rules-ft.sh <<END
#!/bin/bash
# INPUT IP SERVER MANAGEMEN TCP CONNECT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10015 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10012 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10011 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10008 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10007 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10006 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10005 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10004 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10003 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10002 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10001 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 10000 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 8080 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 3128 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 1194 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 109 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 169 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 68 -j ACCEPT

# INPUT IP SERVER MANAGEMEN UDP CONNECT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 2100 -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 2200 -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 5300 -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 7100 -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 7200 -j ACCEPT
iptables -I INPUT -m state --state NEW -m udp -p udp --dport 7300 -j ACCEPT

# INPUT IP SERVER MANAGEMEN TORRENT DISCONNECT
# Block Torrent algo string using Boyer-Moore (bm)
iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" -j DROP
iptables -A FORWARD -m string --algo bm --string "peer_id=" -j DROP
iptables -A FORWARD -m string --algo bm --string ".torrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" -j DROP
iptables -A FORWARD -m string --algo bm --string "torrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "announce" -j DROP
iptables -A FORWARD -m string --algo bm --string "info_hash" -j DROP
iptables -A FORWARD -m string --algo bm --string "/default.ida?" -j DROP
iptables -A FORWARD -m string --algo bm --string ".exe?/c+dir" -j DROP
iptables -A FORWARD -m string --algo bm --string ".exe?/c_tftp" -j DROP
# Block Torrent keys
iptables -A FORWARD -m string --algo kmp --string "peer_id" -j DROP
iptables -A FORWARD -m string --algo kmp --string "BitTorrent" -j DROP
iptables -A FORWARD -m string --algo kmp --string "BitTorrent protocol" -j DROP
iptables -A FORWARD -m string --algo kmp --string "bittorrent-announce" -j DROP
iptables -A FORWARD -m string --algo kmp --string "announce.php?passkey=" -j DROP
# Block Distributed Hash Table (DHT) keywords
iptables -A FORWARD -m string --algo kmp --string "find_node" -j DROP
iptables -A FORWARD -m string --algo kmp --string "info_hash" -j DROP
iptables -A FORWARD -m string --algo kmp --string "get_peers" -j DROP
iptables -A FORWARD -m string --algo kmp --string "announce" -j DROP
iptables -A FORWARD -m string --algo kmp --string "announce_peers" -j DROP

iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
iptables -t nat -I POSTROUTING 1 -s 10.7.0.0/24 -o $ETH -j MASQUERADE
iptables -t nat -I POSTROUTING 1 -s 10.6.0.0/24 -o $ETH -j MASQUERADE
iptables -t nat -I POSTROUTING 1 -s 10.8.0.0/24 -o $ETH -j MASQUERADE
iptables -t nat -I POSTROUTING 1 -s 20.8.0.0/24 -o $ETH -j MASQUERADE

END

chmod +x /usr/bin/rules-ft.sh
systemctl restart netfilter-persistent

chmod +x /usr/bin/rules-ft.sh
cat >/etc/systemd/system/rules-ft.service <<EOF
[Unit]
Description=iptables rules for All Protocol
Before=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/rules-ft.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable rules-ft
systemctl start rules-ft
